### ISSUE TITLE
三人称視点では機能を無効化したい

### ISSUE THREAD

**Issue by lill-la** [hantabaru1014/HeadCullingMask#1]
三人称モードやフリーフォームモード(デスクトップモードでF5やF6でなるやつ)で機能を無効化したい

**Comment by hantabaru1014** [comment]
ですよね。私も思ってました。後で関係しそうな所見てみます。  
もしくは既に良さげなパッチ対象が見つかってるならプルリク大歓迎です！

**Comment by lill-la** [comment]
F5に合わせてUpdateLayerが呼び出せたところまではやってみたけどうまく動かなかったのを置いておきます
https://github.com/lillazk/HeadCullingMask/blob/b1cf282fb78ed934dcb3c4a90d852c6138973c53/HeadCullingMask.cs#L93

**Comment by hantabaru1014** [comment]
動くようになりました。　　
レイヤーの設定をUnity上のGameObjectに強制的に反映させる必要がありました。

1.2.0としてリリースします。ありがとうございました！！
